apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: btp-tos-gate
  
nameSuffix: -tos-gate
bases:
  - ../base/envs
  - ../base/manisfest

patches:
  - target:
      kind: Deployment
      name: btp-tos-gate
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: ns-oracle
            valueFrom:
              configMapKeyRef:
                name:  dev-myconf
                key: ns-oracle
